# Featuring Engineering

In [1]:
import pandas as pd
import sqlalchemy
from dotenv import load_dotenv
import pathlib

import os

parent = pathlib.Path.cwd().parent
ENV_PATH = str(parent) + "/.env/.env"

load_dotenv(ENV_PATH)


DATABASE = os.getenv("DATABASE")
DB_KEY = os.getenv("DB_KEY")
USERNAME = os.getenv("USERNAME")

assert DATABASE and DB_KEY and USERNAME

ENGINE = sqlalchemy.create_engine(f"postgresql+psycopg://{USERNAME}:{DB_KEY}@localhost:5432/{DATABASE}")

In [2]:
query = """
    SELECT * FROM cleaned_data.joined

"""
table = pd.read_sql(query, con=ENGINE, index_col=["zcta", "state"])
features = pd.DataFrame(index=table.index)

print(table.index)
print(features.index)

MultiIndex([('01005', 'MA'),
            ('01013', 'MA'),
            ('01032', 'MA'),
            ('01033', 'MA'),
            ('01039', 'MA'),
            ('01040', 'MA'),
            ('01050', 'MA'),
            ('01060', 'MA'),
            ('01069', 'MA'),
            ('01071', 'MA'),
            ...
            ('99650', 'AK'),
            ('99672', 'AK'),
            ('99701', 'AK'),
            ('99709', 'AK'),
            ('99737', 'AK'),
            ('99741', 'AK'),
            ('99801', 'AK'),
            ('99826', 'AK'),
            ('99829', 'AK'),
            ('99840', 'AK')],
           names=['zcta', 'state'], length=6979)
MultiIndex([('01005', 'MA'),
            ('01013', 'MA'),
            ('01032', 'MA'),
            ('01033', 'MA'),
            ('01039', 'MA'),
            ('01040', 'MA'),
            ('01050', 'MA'),
            ('01060', 'MA'),
            ('01069', 'MA'),
            ('01071', 'MA'),
            ...
            ('99650', 'AK'),
            ('99672', 'AK'),
            ('99701', 'AK'),
            ('99709', 'AK'),
            ('99737', 'AK'),
            ('99741', 'AK'),
            ('99801', 'AK'),
            ('99826', 'AK'),
            ('99829', 'AK'),
            ('99840', 'AK')],
           names=['zcta', 'state'], length=6979)

### Mean+Median Weighted Sum

I created this weighted sum which I use throughout to combine the mean and median curbing the impact of cases where the mean is significantly larger or smaller than the median. This function combines the two values in such a way that, as the mean deviates further from the median, the weighted sum converges toward the median. This prevents extreme values in the mean from having too much influence on the final result.

In [3]:
def mean_median( mean, median):
    u = ((mean-median)/median.replace(0, float("nan")))
    w = (1 - 0.5) / (1 + (u / 2)** 2)
    return (w * mean + (1 - w) * median).fillna(mean)

## 1. Business Index

This is the primary variable that we will be trying to predict.

In [4]:


def business_index(raw, w) -> pd.Series: 
    assert len(w) == 9


    total_est_emp_ratio = raw.estab_total/raw.emp_total
    estab_weighted_sum = (raw.estab_1_4 *w[0]) + (raw.estab_5_9 * w[1]) + (raw.estab_10_19*w[2]) + (raw.estab_20_49*w[3]) + (raw.estab_50_99*w[4]) + (raw.estab_100_249*w[5]) + (raw.estab_250_499*w[6]) + (raw.estab_500_999*w[7]) + (raw.estab_1000_plus*w[8])

    retail_ratio = raw.estab_n08_bus/raw.estab_n01_bus 

    return (estab_weighted_sum/total_est_emp_ratio) * retail_ratio


features["bus_idx"] = business_index(table, (0.9,0.8,0.5, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1 ))   

features.head()

                bus_idx
zcta  state
01005 MA      95.896541
01013 MA     488.853458
01032 MA      14.534320
01033 MA      79.470248
01039 MA      23.190857

# 2. Child Population

In [5]:
features["ch_pop"] = table.child_population / table.total_population

features.head()

                bus_idx    ch_pop
zcta  state
01005 MA      95.896541  0.219808
01013 MA     488.853458  0.201351
01032 MA      14.534320  0.061630
01033 MA      79.470248  0.174606
01039 MA      23.190857  0.156024

## 3. Working Population

In [6]:
features["work_pop"] = table.working_population / table.total_population

## 4. Crime Index

In [7]:
features["crime_idx"] = table.total_crime_index
features.head()

                bus_idx    ch_pop  work_pop  crime_idx
zcta  state
01005 MA      95.896541  0.219808  0.633305       27.0
01013 MA     488.853458  0.201351  0.623050      122.0
01032 MA      14.534320  0.061630  0.222664       16.0
01033 MA      79.470248  0.174606  0.656209       27.0
01039 MA      23.190857  0.156024  0.563253       29.0

## 5. Day Time Population

In [8]:
# features["day_pop"] = table.daytime_population / table.total_population
features["day_pop"] = table.daytime_population_density

## 6. Daytime Workers

In [9]:
features["day_work"] = table.daytime_workers / table.total_population

# 7. Disposable Income

In [10]:
features["disp_inc"] = mean_median(mean=table.average_disposable_income, median=table.median_disposable_income)
    

features.head()

,,bus_idx,ch_pop,work_pop,crime_idx,day_pop,day_work,disp_inc
zcta,state,,,,,,,
01005,MA,95.896541,0.219808,0.633305,27.0,95.4,0.362098,85000.990389
01013,MA,488.853458,0.201351,0.623050,122.0,3111.1,0.235686,59586.934037
01032,MA,14.534320,0.061630,0.222664,16.0,29.7,0.182903,80211.049756
01033,MA,79.470248,0.174606,0.656209,27.0,149.9,0.243922,103291.163424
01039,MA,23.190857,0.156024,0.563253,29.0,72.6,0.353012,93611.292659

## 8. College Tuition

In [11]:
features["coll_tuition"] = table.avg_college_tuition

## 9. Stocks

In [12]:
features["stocks"] = table.avg_value_of_stocks

## 10. Home Value

In [13]:
features["home_val"] = mean_median(mean=table.average_home_value, median=table.median_home_value)

# 11. Net Worth

In [14]:
features["net_worth"] = mean_median(mean=table.average_net_worth, median=table.median_net_worth)

## 12. Consumer Spending

In [15]:
features["cons_spen"] = table.total_consumer_spending

## 13. Urbanity

In [16]:
features["urbanity"] = (table.urban_population - table.rural_population) / (table.urban_population + table.rural_population)

## 14. Age

In [17]:
features["age"] = table.median_male_age + table.median_female_age

## 15. Vacancy

In [18]:
features["vacancy"] = table.vacant_housing_units / table.housing_units

## 16. Income

In [19]:
features["income"] = table.per_capita_income/ table.median_household_income

## 17. SNAP

In [20]:
features["snap"] = (table.food_stamp_households )/ table.total_population

## 18. Education

In [21]:
features["education"] = table.bachelors_degree / table.total_population

## 19. Public Transport

In [22]:
features["pub_trans"] = table.public_transport_users / table.total_population

## 20. Commute

In [23]:
features["commute"] = table.aggregate_commute_time / table.total_commuters

## 21. Tenure

In [24]:
features["tenure"] = (table.renter_occupied - table.owner_occupied) / (table.renter_occupied + table.owner_occupied)

## 22. Vehicle Owner

In [25]:
features["vehicle_owner"] = table.no_vehicle_households / table.total_households
len(features.columns)

22

In [26]:
features.to_sql("features", schema="training_data", con=ENGINE, if_exists="replace")

-1